### ISSUE TITLE
Database Performance Improvements

### ISSUE THREAD

**Issue by z1pti3** [z1pti3/jimiPlugin-event#3]
during correlation each event is pulled then pushed back to the DB including all of the document that already exists. This can be improve by using Mongo array commands to push only the updates.

Furthermore, CPU can be hit hard with the  correlation engine and it would be wroth looking at how the number of loops can be reduced.

**Comment by ghost** [comment]
Further testing of this has also shown a slow down in the performance of correlations when the events in the system exceed 10k currently active
